baseurl = "https://rafaelbeloduarte.github.io/"
title = "Rafael Belo Duarte"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"
publishdir = "../rafaelbeloduarte.github.io"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Rafael Belo Duarte"
    info = "Engenheiro Químico"
#    description = "Aqui encontrarás meu currículo e projetos realizados."
    keywords = "blog,engenharia,engenharia química"
    # avatarurl = "img/icon_32.png"
    
    dateformat = "02/01/2006"

    timeformat = "03:04"

    favicon_32 = "/img/icon_32.png"
    favicon_16 = "/img/icon_16.png"

    footercontent = "rafaelbeloduarte@pm.me"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)

    colorscheme = "auto"

# Social links
[[params.social]]
    name = "Github"
    #icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/rafaelbeloduarte/"
# [[params.social]]
#     name = "LinkedIn"
#     icon = "fab fa-linkedin"
#     weight = 2
#     url = "https://www.linkedin.com/in/rafaelbeloduarte/"
[[params.social]]
    name = "Lattes"
    #icon = "fas fa-university fa-2x"
    weight = 2
    url = "http://lattes.cnpq.br/7196186096336881"

[languages]
    [languages.en]
      languagename = "English"
        
        [languages.en.params]
            author = "Rafael Belo Duarte"
            info = "Chemical Engineer"
            description = "My papers, essays, and classroom aid material." 
            keywords = "blog,engineering,chemical engineering"
            footercontent = "rafaelbeloduarte@pm.me"
            dateformat = "Jan 02, 2006"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 10
            url = "/posts/"

            [[languages.en.menu.main]]
            name = "Publications"
            weight = 20
            url = "/publications/"

            [[languages.en.menu.main]]
            name = "Tags"
            weight = 30
            url = "/tags/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 40
            url = "/contact"


    [languages.pt-br]
       languagename = "Português"

        [languages.pt-br.params]
            author = "Rafael Belo Duarte"
            info = "Engenheiro Químico"
            description = "Meus artigos, textos, e material de auxílio em sala de aula."
            keywords = "blog,engenharia,engenharia química"
            footercontent = "rafaelbeloduarte@pm.me"
            title = "Rafael Belo Duarte"

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Textos"
            weight = 10
            url = "/posts/"

            [[languages.pt-br.menu.main]]
            name = "Publicações"
            weight = 20
            url = "/publications/"
            
            [[languages.pt-br.menu.main]]
            name = "Etiquetas"
            weight = 30
            url = "/tags/"

            [[languages.pt-br.menu.main]]
            name = "Contato"
            weight = 40
            url = "/contato"
